USE probability;
CREATE TABLE MONTY_HALL(
	ID INT AUTO_INCREMENT NOT NULL
    ,TRANSACTION_ID INT NOT NULL
    ,DOOR_SELECTED INT NOT NULL
    ,DOOR_CORRECT INT NOT NULL
    ,DOOR_SUGGESTION INT NOT NULL
    ,DATE_START VARCHAR(100) NOT NULL
    ,DATE_FINISH VARCHAR(100) NOT NULL
    ,FINISHED INT NOT NULL
    ,RESULT VARCHAR(100) NOT NULL
    
    ,CONSTRAINT PK_MONTY_HALL PRIMARY KEY(ID)
);